<?php

/**
 * Implements hook_menu().
 */
function invite_menu() {
  $items['admin/config/people/invite'] = array(
    'title' => 'Invites',
    'page callback' => 'invite_admin_overview',
    'access arguments' => array('administer invitations'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'invite.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_entity_info().
 */
function invite_entity_info() {
  $return['invite'] = array(
    'label' => t('Invite'),
    'base table' => 'invite',
    'uri callback' => 'invite_uri',
    'fieldable' => TRUE,
    'entity keys' => array(
      'id' => 'iid',
    ),
    'bundles' => array(
      'invite' => array(
        'label' => t('Invite'),
        'admin' => array(
          'path' => 'admin/config/people/invite',
          'access arguments' => array('administer invitations'),
        ),
      ),
    ),
    'static cache' => TRUE,
    'view modes' => array(
      'full' => array(
        'label' => t('Full invite'),
        'custom settings' => FALSE,
      ),
    ),
  );
  return $return;
}

/**
 * Implements hook_permission().
 */
function invite_permission() {
  return array(
    'administer invitations' => array(
      'title' => t('administer invitations'),
      'description' => t('Administer all invitations'),
    ),
    'send invitations' => array(
      'title' => t('send invitations'),
      'description' => t('Send invitations to other users.'),
    ),
  );
}
