<?php
// $Id$

/**
 * @file
 * Allows your users to terminate user accounts by withdrawing their
 * invitation.
 */

/**
 * Implements hook_invite().
 *
 * Withdrawing an invitation leads to termination of invited user's account.
 */
function invite_cancel_account_invite($op, $args) {
  switch ($op) {
    case 'cancel':
      if (user_access('withdraw accepted invitations')) {
        if ($account = user_load_by_mail($args['email'])) {
          // @todo Make $method configurable.
          user_cancel(array(), $account->uid, 'user_cancel_delete');
        }
      }
      break;
  }
}
